version: "3.8"
services:
  api:
    build: ./infra/php
    volumes:
      - ./app:/app

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
