version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./app:/app
      - vendor:/app/vendor

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/app
      - vendor:/app/vendor
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  vendor:
